# -*- coding: utf-8 -*-
"""Task_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1REvwMA7K0nu2Ir_LUlkFGdNbwSI-ycY5
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

df_comments = pd.read_csv("/content/comments.csv")
df_comments

df_comments.info()

df_comments.isnull().sum()

df_comments["emoji used"].value_counts()

df_comments['Hashtags used count'].value_counts().plot(kind="pie", autopct='%1.1f%%')
plt.show()

df_follows = pd.read_csv("/content/follows.csv")
df_follows

df_follows.isnull().sum()

df_follows["is follower active"].value_counts()

df_follows["followee Acc status"].value_counts()

df_follows = df_follows.replace("Private", "private")
df_follows

df_follows["followee Acc status"].value_counts().plot(kind="bar")
plt.show()

df_likes = pd.read_csv("/content/likes.csv")
df_likes

df_likes.isnull().sum()

df_likes.duplicated().sum()

df_likes["following or not"].value_counts().plot(kind="bar", xlabel="Following or not", ylabel="Count")
plt.show()

df_likes["like type"].value_counts()

df_likes["like type"].value_counts().plot(kind="bar", xlabel = "Like type", ylabel="Count")
plt.show()

df_users = pd.read_csv("/content/users.csv")
df_users

df_users["private/public"].value_counts()

df_users["post count"].max()

plt.hist(df_users["post count"], range = [10, 2500])
plt.xlabel("Post count")
plt.ylabel("Count")
plt.show()

df_users["Verified status"].value_counts()

df_users["Verified status"].value_counts()

df_tags = pd.read_csv("/content/tags.csv")
df_tags

df_tags["location"].value_counts()

df_photos = pd.read_csv("/content/photos.csv")
df_photos

df_photos["Insta filter used"].value_counts().plot(kind="bar", xlabel="Was Insta Filter Used", ylabel="Count")
plt.show()

df_phototags = pd.read_csv("/content/photo_tags.csv")
df_phototags